# AUS tweets sentiment on the goverment medates

## Import the key libraires

In [1]:
#Load the function libraries into the proramming enviroment
import numpy as np
import pandas as pd

#Load the tokenizer and the text feature extractor libraires into the programming
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

#Basic data process and splitting tool loading...
from sklearn.model_selection import train_test_split

#Import the Logistic regression model into the programming
from sklearn.linear_model import LogisticRegression

#Perfromacne analysis libray 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report


In [2]:
#Define the counter vectorisers
counter_v = 'count_v'
counter_t = 'count_t'

def data_process_lr_model(dataset, vectoriser,random_state):
    #Collecte the dataset and spleat the feature and the 
    x = dataset['Lemma']
    y = dataset['Sentiment']
    
    #Extract the sentiment form the text lemma dataset by using the counter vectoriser dataset
    cv = CountVectorizer()
    tv = TfidfVectorizer()
    
    
    #Tokenised the lemma dataset
    #Funciton for the counter vectorieser
    if vectoriser == 'count_v':
        vec_feature= cv.fit_transform(x.astype('U'))
        
    #Function for the token id based vectoriser 
    elif vectoriser == 'count_t':
        vec_feature = tv.fit_transform(x.astype('U'))
        
    
    #Split the the dataset for the macine learning training and validation    
    x_train, x_test, y_train, y_test = train_test_split(vec_feature,y, test_size=0.25, random_state=random_state)
              
 #Logistic regression model for the predicting sentiment analysis
    lr = LogisticRegression()
    lr.fit(x_train,y_train)
    #Check model performance accuracy
    lr_score = lr.score(x_train,y_train)
    print('Model perfoemce socre:',lr_score)
    #Predicting the labels form the dataset
    y_pred=lr.predict(x_test)
    
    #Machine learning model perfromacne analysis
    print('model confusion matrix\n')
    cmet = confusion_matrix(y_test,y_pred)
    print(cmet,'\n')
    print('model classificaiton report\n')
    print(classification_report(y_pred,y_test))

# Face mask sentiment analysis using SVM

In [3]:
#Load the dataset
mask_data= pd.read_csv('face_mask_sentiment_score.csv')
mask_data.head()#Print the head of the dataset

date  \
0  2020-12-31 23:46:53+00:00   
1  2020-12-31 23:22:47+00:00   
2  2020-12-31 22:46:38+00:00   
3  2020-12-31 22:29:51+00:00   
4  2020-12-31 22:23:13+00:00   

                                             content  \
0  victorian health minister clarified rules arou...   
1  1996367 @_teslatom _ev 2playa 66 michael. thin...   
2  mask 😷 wearing deemed much burden ppl nsw acco...   
3  @_teslatom _ev 1996367 2playa 66 happy 2020.48...   
4  ludicrous, takes entire press conference expla...   

                                          POS_tagged  \
0  [('victorian', 'a'), ('health', 'n'), ('minist...   
1  [('1996367', None), ('@', 'a'), ('_teslatom', ...   
2  [('mask', 'n'), ('😷', None), ('wearing', 'n'),...   
3  [('@', 'a'), ('_teslatom', 'n'), ('_ev', 'n'),...   
4  [('ludicrous', 'a'), (',', None), ('takes', 'v...   

                                               Lemma  Polarity  Sentiment  
0  victorianhealthministerclarifyrulearoundmaskin...       0.0          0  
1  1996367@_teslatom_ev2playa66michael.thinkbugfi...       0.0          0  
2  mask😷wearingdeemmuchburdenpplnswaccord.cricket...       0.0          0  
3  @_teslatom_ev19963672playa66happy2020.48.30guy😂🙏💥       0.0          0  
4  ludicrous,takeentirepressconferenceexplain“rul...       0.0          0

## Model with the counter vectorizer

In [13]:
mask_score = data_process_lr_model(mask_data,counter_v, random_state=9)

Model perfoemce socre: 0.9869259135098893
model confusion matrix

[[   0   21    0]
 [   0 2913    1]
 [   0   49    0]] 

model classificaiton report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       1.00      0.98      0.99      2983
           1       0.00      0.00      0.00         1

    accuracy                           0.98      2984
   macro avg       0.33      0.33      0.33      2984
weighted avg       1.00      0.98      0.99      2984



/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Model with the TFID Vectorizer

In [22]:
mask_score_tfid = data_process_lr_model(mask_data,counter_t, random_state=5)

Model perfoemce socre: 0.9791038104816181
model confusion matrix

[[   0   14    0]
 [   0 2917    0]
 [   0   52    1]] 

model classificaiton report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       1.00      0.98      0.99      2983
           1       0.02      1.00      0.04         1

    accuracy                           0.98      2984
   macro avg       0.34      0.66      0.34      2984
weighted avg       1.00      0.98      0.99      2984



/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Lockdown Sentiment analysis using the machine learning model

In [23]:
lockdown_data = pd.read_csv('lockdwon_sentiment_score.csv')
lockdown_data.head()

date  \
0  2020-10-30 23:56:05+00:00   
1  2020-10-30 23:48:39+00:00   
2  2020-10-30 23:32:28+00:00   
3  2020-10-30 23:26:27+00:00   
4  2020-10-30 21:58:31+00:00   

                                             content  \
0  lockdown works short term. ultimately best str...   
1  finish inktober2020 smile. thank reacted, comm...   
2  lmao melb defs going 3rd 4th lockdown. people ...   
3  im sorry, britain. boris failed again. 4 weeks...   
4  wish people thought you. it’s really awful see...   

                                          POS_tagged  \
0  [('lockdown', 'a'), ('works', 'v'), ('short', ...   
1  [('finish', 'a'), ('inktober2020', 'n'), ('smi...   
2  [('lmao', 'n'), ('melb', 'n'), ('defs', 'v'), ...   
3  [('im', 'n'), ('sorry', 'n'), (',', None), ('b...   
4  [('wish', 'a'), ('people', 'n'), ('thought', '...   

                                               Lemma  Polarity  Sentiment  
0  lockdownworkshortterm.ultimatelybeststrategylo...       0.0          0  
1  finishinktober2020smile.thankreact,comment,sha...       0.0          0  
2          lmaomelbdefsgo3rd4thlockdown.peoplefully’       0.0          0  
3  imsorry,britain.borisfail.4weeksagesayimplemen...       0.0          0  
4  wishpeoplethink.’reallyawfulseemanycasedeath.e...       0.0          0

## Lockdown data sentiment analysis with the counter vectorizer

In [28]:
lockdown_socre = data_process_lr_model(lockdown_data,counter_v, random_state=454)

Model perfoemce socre: 0.9925004933885928
model confusion matrix

[[   0   25    0]
 [   1 3322    1]
 [   1   29    0]] 

model classificaiton report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         2
           0       1.00      0.98      0.99      3376
           1       0.00      0.00      0.00         1

    accuracy                           0.98      3379
   macro avg       0.33      0.33      0.33      3379
weighted avg       1.00      0.98      0.99      3379



## Lockdown data sentiment analysis with the TFID vectorizer

In [161]:
lockdown_scorer_tfid = data_process_lr_model(lockdown_data,counter_t, random_state=454)

Model perfoemce socre: 0.9830274324057627
model confusion matrix

[[   0   25    0]
 [   0 3324    0]
 [   0   30    0]] 

model classificaiton report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       1.00      0.98      0.99      3379
           1       0.00      0.00      0.00         0

    accuracy                           0.98      3379
   macro avg       0.33      0.33      0.33      3379
weighted avg       1.00      0.98      0.99      3379



/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# COVID-19AU data machine learning based setntiment analysis

In [44]:
covid_data = pd.read_csv('covid19_sentiment_score.csv')
covid_data.head()

date  \
0  2020-10-30 02:49:20+00:00   
1  2020-10-29 03:12:56+00:00   
2  2020-10-29 00:47:25+00:00   
3  2020-10-24 23:45:24+00:00   
4  2020-10-24 09:13:34+00:00   

                                             content  \
0  talking things queensland borders today’s pres...   
1  hand sanitiser sold australia contain enough a...   
2  saturday night blokes night will occur wives g...   
3                                   nailed covid19au   
4  1 week election, pandemic still raging world w...   

                                          POS_tagged  \
0  [('talking', 'v'), ('things', 'n'), ('queensla...   
1  [('hand', 'n'), ('sanitiser', 'n'), ('sold', '...   
2  [('saturday', 'a'), ('night', 'n'), ('blokes',...   
3              [('nailed', 'v'), ('covid19au', 'n')]   
4  [('1', None), ('week', 'n'), ('election', 'n')...   

                                               Lemma  Polarity  Sentiment  
0    talkthingqueenslandbordertoday’pressercovid19au       0.0          0  
1  handsanitisersellaustraliacontainenoughalcohol...       0.0          0  
2  saturdaynightblokenightoccurwifegoannualjauntt...       0.0          0  
3                                      nailcovid19au       0.0          0  
4  1weekelection,pandemicstillragworldwide,lettru...       0.0          0

## COVID-19au data with the counter vectorizer

In [148]:
covid_score_cv = data_process_lr_model(covid_data, counter_v, random_state=45)

Model perfoemce socre: 0.9955015744489428
model confusion matrix

[[  0   1   0]
 [  0 737   0]
 [  0   3   0]] 

model classificaiton report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       1.00      0.99      1.00       741
           1       0.00      0.00      0.00         0

    accuracy                           0.99       741
   macro avg       0.33      0.33      0.33       741
weighted avg       1.00      0.99      1.00       741



/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## COVID-19au data with the TFID vectorizer

In [145]:
covid_score_tfid = data_process_lr_model(covid_data, counter_t, random_state=5)

Model perfoemce socre: 0.9946018893387314
model confusion matrix

[[  0   2   0]
 [  0 733   0]
 [  0   6   0]] 

model classificaiton report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       1.00      0.99      0.99       741
           1       0.00      0.00      0.00         0

    accuracy                           0.99       741
   macro avg       0.33      0.33      0.33       741
weighted avg       1.00      0.99      0.99       741



/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Qurantine data sentiment analysis using machine learning model

In [70]:
qurantie_data = pd.read_csv('quarantine_sentiment_score.csv')
qurantie_data.head()

date  \
0  2020-10-30 21:22:16+00:00   
1  2020-10-30 20:10:28+00:00   
2  2020-10-30 19:09:21+00:00   
3  2020-10-30 18:55:47+00:00   
4  2020-10-30 18:18:47+00:00   

                                             content  \
0                                        quarantine?   
1  cristiano ronaldo tested negative covid 19 qua...   
2  evening cravings 💕 hightea quarantine style co...   
3  today supposed d7 quarantine im restarting cou...   
4                        finally quarantine day 14 😌   

                                          POS_tagged  \
0                 [('quarantine', 'n'), ('?', None)]   
1  [('cristiano', 'n'), ('ronaldo', 'n'), ('teste...   
2  [('evening', 'v'), ('cravings', 'n'), ('💕', 'n...   
3  [('today', 'n'), ('supposed', 'v'), ('d7', 'a'...   
4  [('finally', 'r'), ('quarantine', 'a'), ('day'...   

                                               Lemma  Polarity  Sentiment  
0                                        quarantine?       0.0          0  
1  cristianoronaldotestnegativecovid19quarantine....       0.0          0  
2  evencraving💕highteaquarantinestylecookyhightea...       0.0          0  
3         todaysupposed7quarantineimrestartcountdown       0.0          0  
4                            finallyquarantineday14😌       0.0          0

## Qurantien data with the counter vectorizer

In [138]:
qurantie_score_cv = data_process_lr_model(qurantie_data, counter_v, random_state=30)

Model perfoemce socre: 0.9916960241570206
model confusion matrix

[[   0    9    0]
 [   0 1306    0]
 [   0   10    0]] 

model classificaiton report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       1.00      0.99      0.99      1325
           1       0.00      0.00      0.00         0

    accuracy                           0.99      1325
   macro avg       0.33      0.33      0.33      1325
weighted avg       1.00      0.99      0.99      1325



/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Qurantien data with the TFID vectorizer

In [134]:
qurantie_score_cv = data_process_lr_model(qurantie_data, counter_t, random_state=3)

Model perfoemce socre: 0.9841469552088575
model confusion matrix

[[   0    5    0]
 [   0 1313    0]
 [   0    7    0]] 

model classificaiton report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       1.00      0.99      1.00      1325
           1       0.00      0.00      0.00         0

    accuracy                           0.99      1325
   macro avg       0.33      0.33      0.33      1325
weighted avg       1.00      0.99      1.00      1325



/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Social Distancing sentiment data analysis with the machine learning model

In [88]:
soc_data = pd.read_csv('soc_distance_sentiment_score.csv')
soc_data.head()

date  \
0  2020-10-30 22:06:12+00:00   
1  2020-10-30 21:09:12+00:00   
2  2020-10-30 19:36:57+00:00   
3  2020-10-30 11:51:33+00:00   
4  2020-10-30 11:04:50+00:00   

                                             content  \
0                               social distancing w/   
1  really impressed _nz strongly recommending mas...   
2  great work australia weve mildest flu season e...   
3  population especially urban metropolis, people...   
4  tapi ada sedikit kelakar social distancing nnt...   

                                          POS_tagged  \
0  [('social', 'a'), ('distancing', 'n'), ('w/', ...   
1  [('really', 'r'), ('impressed', 'a'), ('_nz', ...   
2  [('great', 'a'), ('work', 'n'), ('australia', ...   
3  [('population', 'n'), ('especially', 'r'), ('u...   
4  [('tapi', 'n'), ('ada', 'v'), ('sedikit', 'a')...   

                                               Lemma  Polarity  Sentiment  
0                                 socialdistancingw/       0.0          0  
1  reallyimpressed_nzstronglyrecommendmaskremindp...       0.0          0  
2  greatworkaustraliawevemildfluseasonever.highra...       0.0          0  
3  populationespeciallyurbanmetropolis,peoplepers...       0.0          0  
4  tapiadasedikitkelakarsocialdistancennti🤣🤣🤣tpmn...       0.0          0

## SOC data with the counter vectorizer

In [130]:
soc_score = data_process_lr_model(soc_data, counter_v, random_state=5000)

Model perfoemce socre: 0.9927236971484759
model confusion matrix

[[   0   11    0]
 [   0 1666    0]
 [   0   17    1]] 

model classificaiton report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       1.00      0.98      0.99      1694
           1       0.06      1.00      0.11         1

    accuracy                           0.98      1695
   macro avg       0.35      0.66      0.37      1695
weighted avg       1.00      0.98      0.99      1695



/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## SOC data with the tfid vectorizer

In [104]:
soc_score = data_process_lr_model(soc_data, counter_v, random_state=5000)

Model perfoemce socre: 0.9927236971484759
model confusion matrix

[[   0   11    0]
 [   0 1666    0]
 [   0   17    1]] 

model classificaiton report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       1.00      0.98      0.99      1694
           1       0.06      1.00      0.11         1

    accuracy                           0.98      1695
   macro avg       0.35      0.66      0.37      1695
weighted avg       1.00      0.98      0.99      1695



/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Vaccine data sentiment analysis using machine learning model

In [105]:
vacc_data = pd.read_csv('vaccine_sentiment_score.csv')
vacc_data.head()

date  \
0  2020-10-30 21:43:08+00:00   
1  2020-10-30 15:43:24+00:00   
2  2020-10-30 14:00:59+00:00   
3  2020-10-30 09:37:53+00:00   
4  2020-10-30 06:36:20+00:00   

                                             content  \
0        _fletcher hope ➕decent president ➕vaccine ✅   
1  date someone who..? 1 - done 2 - lyfe 3 - dont...   
2         offer free covid vaccines apple fanboys 😉😉   
3              shaa allah ate. vaccine nalang kulang   
4  great modig pm modi says indians will coronavi...   

                                          POS_tagged  \
0  [('_fletcher', None), ('hope', 'n'), ('➕decent...   
1  [('date', 'n'), ('someone', 'n'), ('..', 'v'),...   
2  [('offer', 'n'), ('free', 'a'), ('covid', 'n')...   
3  [('shaa', 'n'), ('allah', 'n'), ('ate', 'n'), ...   
4  [('great', 'a'), ('modig', 'n'), ('pm', 'n'), ...   

                                               Lemma  Polarity  Sentiment  
0             _fletcherhope➕decentpresident➕vaccine✅       0.0          0  
1  datesomeone..?1-do2-lyfe3-dontthink?4-nahh..5-...       0.0          0  
2                offerfreecovidvaccineapplefanboys😉😉       0.0          0  
3                   shaaallahate.vaccinenalangkulang       0.0          0  
4  greatmodigpmmodisayindiancoronavirusvaccine,ex...       0.0          0

## Vaccine dataset analysis with the counter vectorizer

In [120]:
vacc_score = data_process_lr_model(vacc_data, counter_v, random_state=67)

Model perfoemce socre: 0.9947437582128777
model confusion matrix

[[  0   3   0]
 [  0 497   0]
 [  0   8   0]] 

model classificaiton report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       1.00      0.98      0.99       508
           1       0.00      0.00      0.00         0

    accuracy                           0.98       508
   macro avg       0.33      0.33      0.33       508
weighted avg       1.00      0.98      0.99       508



/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Vaccine dataset analysis with the tfid vectorizer

In [129]:
vacc_score_tfid = data_process_lr_model(vacc_data, counter_t, random_state=568)

Model perfoemce socre: 0.988173455978975
model confusion matrix

[[  0   1   0]
 [  0 502   0]
 [  0   5   0]] 

model classificaiton report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       1.00      0.99      0.99       508
           1       0.00      0.00      0.00         0

    accuracy                           0.99       508
   macro avg       0.33      0.33      0.33       508
weighted avg       1.00      0.99      0.99       508



/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
