# AUS tweets sentiment on the goverment medates

## Import the key libraires

In [1]:
#Load the function libraries into the proramming enviroment
import numpy as np
import pandas as pd

#Load the tokenizer and the text feature extractor libraires into the programming
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

#Basic data process and splitting tool loading...
from sklearn.model_selection import train_test_split

#Import the support vector machine model into the programming
from sklearn.svm import SVC

#Perfromacne analysis libray 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report


In [2]:
#Define the counter vectorisers
counter_v = 'count_v'
counter_t = 'count_t'

def data_process_svm_model(dataset, vectoriser,random_state):
    #Collecte the dataset and spleat the feature and the 
    x = dataset['Lemma']
    y = dataset['Sentiment']
    
    #Extract the sentiment form the text lemma dataset by using the counter vectoriser dataset
    cv = CountVectorizer()
    tv = TfidfVectorizer()
    
    
    #Tokenised the lemma dataset
    #Funciton for the counter vectorieser
    if vectoriser == 'count_v':
        vec_feature= cv.fit_transform(x.astype('U'))
        
    #Function for the token id based vectoriser 
    elif vectoriser == 'count_t':
        vec_feature = tv.fit_transform(x.astype('U'))
        
    
    #Split the the dataset for the macine learning training and validation    
    x_train, x_test, y_train, y_test = train_test_split(vec_feature,y, test_size=0.25, random_state=random_state)
    from imblearn.over_sampling import SMOTE
    sm = SMOTE(random_state=42)
    x_train_smote, y_train_smote = sm.fit_resample(x_train, y_train)
    #Support vector machine based machine learning model
    C= 1.0
    svc= SVC(kernel='linear', C=1).fit(x_train_smote,y_train_smote)
    y_pred = svc.predict(x_test)
    
    print("No. of features in each class\n ", y_train.value_counts())
    print("No. of features in each class after SMOTE\n ", y_train_smote.value_counts())
    
    
    #Machine learning model perfromacne analysis
    print('model confusion matrix\n')
    cmet = confusion_matrix(y_test,y_pred)
    print(cmet,'\n')
    print('model classificaiton report\n')
    print(classification_report(y_pred,y_test))

# Face mask sentiment analysis using SVM

In [3]:
#Load the dataset
mask_data= pd.read_csv('face_mask_sentiment_score.csv')
mask_data.head()#Print the head of the dataset

date  \
0  2020-12-31 23:46:53+00:00   
1  2020-12-31 23:22:47+00:00   
2  2020-12-31 22:46:38+00:00   
3  2020-12-31 22:29:51+00:00   
4  2020-12-31 22:23:13+00:00   

                                             content  \
0  victorian health minister clarified rules arou...   
1  1996367 @_teslatom _ev 2playa 66 michael. thin...   
2  mask 😷 wearing deemed much burden ppl nsw acco...   
3  @_teslatom _ev 1996367 2playa 66 happy 2020.48...   
4  ludicrous, takes entire press conference expla...   

                                          POS_tagged  \
0  [('victorian', 'a'), ('health', 'n'), ('minist...   
1  [('1996367', None), ('@', 'a'), ('_teslatom', ...   
2  [('mask', 'n'), ('😷', None), ('wearing', 'n'),...   
3  [('@', 'a'), ('_teslatom', 'n'), ('_ev', 'n'),...   
4  [('ludicrous', 'a'), (',', None), ('takes', 'v...   

                                               Lemma  Polarity  Sentiment  
0  victorianhealthministerclarifyrulearoundmaskin...       0.0          0  
1  1996367@_teslatom_ev2playa66michael.thinkbugfi...       0.0          0  
2  mask😷wearingdeemmuchburdenpplnswaccord.cricket...       0.0          0  
3  @_teslatom_ev19963672playa66happy2020.48.30guy😂🙏💥       0.0          0  
4  ludicrous,takeentirepressconferenceexplain“rul...       0.0          0

## Model with the counter vectorizer

In [4]:
mask_score = data_process_svm_model(mask_data,counter_v, random_state=11)

No. of features in each class
   0    8751
 1     140
-1      58
Name: Sentiment, dtype: int64
No. of features in each class after SMOTE
   0    8751
-1    8751
 1    8751
Name: Sentiment, dtype: int64
model confusion matrix

[[   8    7    0]
 [1997  862   67]
 [  17   20    6]] 

model classificaiton report

              precision    recall  f1-score   support

          -1       0.53      0.00      0.01      2022
           0       0.29      0.97      0.45       889
           1       0.14      0.08      0.10        73

    accuracy                           0.29      2984
   macro avg       0.32      0.35      0.19      2984
weighted avg       0.45      0.29      0.14      2984



## Model with the TFID Vectorizer

In [5]:
mask_score_tfid = data_process_svm_model(mask_data,counter_t, random_state=7)

No. of features in each class
   0    8768
 1     131
-1      50
Name: Sentiment, dtype: int64
No. of features in each class after SMOTE
   0    8768
-1    8768
 1    8768
Name: Sentiment, dtype: int64
model confusion matrix

[[   3   20    0]
 [   2 2854   53]
 [   0   32   20]] 

model classificaiton report

              precision    recall  f1-score   support

          -1       0.13      0.60      0.21         5
           0       0.98      0.98      0.98      2906
           1       0.38      0.27      0.32        73

    accuracy                           0.96      2984
   macro avg       0.50      0.62      0.51      2984
weighted avg       0.97      0.96      0.96      2984



# Lockdown Sentiment analysis using the machine learning model

In [6]:
lockdown_data = pd.read_csv('lockdwon_sentiment_score.csv')
lockdown_data.head()

date  \
0  2020-10-30 23:56:05+00:00   
1  2020-10-30 23:48:39+00:00   
2  2020-10-30 23:32:28+00:00   
3  2020-10-30 23:26:27+00:00   
4  2020-10-30 21:58:31+00:00   

                                             content  \
0  lockdown works short term. ultimately best str...   
1  finish inktober2020 smile. thank reacted, comm...   
2  lmao melb defs going 3rd 4th lockdown. people ...   
3  im sorry, britain. boris failed again. 4 weeks...   
4  wish people thought you. it’s really awful see...   

                                          POS_tagged  \
0  [('lockdown', 'a'), ('works', 'v'), ('short', ...   
1  [('finish', 'a'), ('inktober2020', 'n'), ('smi...   
2  [('lmao', 'n'), ('melb', 'n'), ('defs', 'v'), ...   
3  [('im', 'n'), ('sorry', 'n'), (',', None), ('b...   
4  [('wish', 'a'), ('people', 'n'), ('thought', '...   

                                               Lemma  Polarity  Sentiment  
0  lockdownworkshortterm.ultimatelybeststrategylo...       0.0          0  
1  finishinktober2020smile.thankreact,comment,sha...       0.0          0  
2          lmaomelbdefsgo3rd4thlockdown.peoplefully’       0.0          0  
3  imsorry,britain.borisfail.4weeksagesayimplemen...       0.0          0  
4  wishpeoplethink.’reallyawfulseemanycasedeath.e...       0.0          0

## Lockdown data sentiment analysis with the counter vectorizer

In [7]:
lockdown_socre = data_process_svm_model(lockdown_data,counter_v, random_state=9)

No. of features in each class
   0    9954
 1     112
-1      68
Name: Sentiment, dtype: int64
No. of features in each class after SMOTE
   0    9954
-1    9954
 1    9954
Name: Sentiment, dtype: int64
model confusion matrix

[[   7   10    5]
 [ 122  974 2236]
 [   0   11   14]] 

model classificaiton report

              precision    recall  f1-score   support

          -1       0.32      0.05      0.09       129
           0       0.29      0.98      0.45       995
           1       0.56      0.01      0.01      2255

    accuracy                           0.29      3379
   macro avg       0.39      0.35      0.19      3379
weighted avg       0.47      0.29      0.14      3379



## Lockdown data sentiment analysis with the TFID vectorizer

In [8]:
lockdown_scorer_tfid = data_process_svm_model(lockdown_data,counter_t, random_state=15)

No. of features in each class
   0    9971
 1     106
-1      57
Name: Sentiment, dtype: int64
No. of features in each class after SMOTE
   0    9971
-1    9971
 1    9971
Name: Sentiment, dtype: int64
model confusion matrix

[[   1   32    0]
 [   0 3315    0]
 [   1   30    0]] 

model classificaiton report

              precision    recall  f1-score   support

          -1       0.03      0.50      0.06         2
           0       1.00      0.98      0.99      3377
           1       0.00      0.00      0.00         0

    accuracy                           0.98      3379
   macro avg       0.34      0.49      0.35      3379
weighted avg       1.00      0.98      0.99      3379



/home/dp/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# COVID-19AU data machine learning based setntiment analysis

In [9]:
covid_data = pd.read_csv('covid19_sentiment_score.csv')
covid_data.head()

date  \
0  2020-10-30 02:49:20+00:00   
1  2020-10-29 03:12:56+00:00   
2  2020-10-29 00:47:25+00:00   
3  2020-10-24 23:45:24+00:00   
4  2020-10-24 09:13:34+00:00   

                                             content  \
0  talking things queensland borders today’s pres...   
1  hand sanitiser sold australia contain enough a...   
2  saturday night blokes night will occur wives g...   
3                                   nailed covid19au   
4  1 week election, pandemic still raging world w...   

                                          POS_tagged  \
0  [('talking', 'v'), ('things', 'n'), ('queensla...   
1  [('hand', 'n'), ('sanitiser', 'n'), ('sold', '...   
2  [('saturday', 'a'), ('night', 'n'), ('blokes',...   
3              [('nailed', 'v'), ('covid19au', 'n')]   
4  [('1', None), ('week', 'n'), ('election', 'n')...   

                                               Lemma  Polarity  Sentiment  
0    talkthingqueenslandbordertoday’pressercovid19au       0.0          0  
1  handsanitisersellaustraliacontainenoughalcohol...       0.0          0  
2  saturdaynightblokenightoccurwifegoannualjauntt...       0.0          0  
3                                      nailcovid19au       0.0          0  
4  1weekelection,pandemicstillragworldwide,lettru...       0.0          0

## COVID-19au data with the counter vectorizer

In [10]:
covid_score_cv = data_process_svm_model(covid_data, counter_v, random_state=38)

No. of features in each class
   0    2206
 1      11
-1       6
Name: Sentiment, dtype: int64
No. of features in each class after SMOTE
   0    2206
 1    2206
-1    2206
Name: Sentiment, dtype: int64
model confusion matrix

[[  0   0   0]
 [477 166  95]
 [  2   0   1]] 

model classificaiton report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00       479
           0       0.22      1.00      0.37       166
           1       0.33      0.01      0.02        96

    accuracy                           0.23       741
   macro avg       0.19      0.34      0.13       741
weighted avg       0.09      0.23      0.08       741



/home/dp/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## COVID-19au data with the TFID vectorizer

In [11]:
covid_score_tfid = data_process_svm_model(covid_data, counter_t, random_state=899)

No. of features in each class
   0    2205
 1      12
-1       6
Name: Sentiment, dtype: int64
No. of features in each class after SMOTE
   0    2205
-1    2205
 1    2205
Name: Sentiment, dtype: int64
model confusion matrix

[[738   1]
 [  2   0]] 

model classificaiton report

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       740
           1       0.00      0.00      0.00         1

    accuracy                           1.00       741
   macro avg       0.50      0.50      0.50       741
weighted avg       1.00      1.00      1.00       741



# Qurantine data sentiment analysis using machine learning model

In [12]:
qurantie_data = pd.read_csv('quarantine_sentiment_score.csv')
qurantie_data.head()

date  \
0  2020-10-30 21:22:16+00:00   
1  2020-10-30 20:10:28+00:00   
2  2020-10-30 19:09:21+00:00   
3  2020-10-30 18:55:47+00:00   
4  2020-10-30 18:18:47+00:00   

                                             content  \
0                                        quarantine?   
1  cristiano ronaldo tested negative covid 19 qua...   
2  evening cravings 💕 hightea quarantine style co...   
3  today supposed d7 quarantine im restarting cou...   
4                        finally quarantine day 14 😌   

                                          POS_tagged  \
0                 [('quarantine', 'n'), ('?', None)]   
1  [('cristiano', 'n'), ('ronaldo', 'n'), ('teste...   
2  [('evening', 'v'), ('cravings', 'n'), ('💕', 'n...   
3  [('today', 'n'), ('supposed', 'v'), ('d7', 'a'...   
4  [('finally', 'r'), ('quarantine', 'a'), ('day'...   

                                               Lemma  Polarity  Sentiment  
0                                        quarantine?       0.0          0  
1  cristianoronaldotestnegativecovid19quarantine....       0.0          0  
2  evencraving💕highteaquarantinestylecookyhightea...       0.0          0  
3         todaysupposed7quarantineimrestartcountdown       0.0          0  
4                            finallyquarantineday14😌       0.0          0

## Qurantien data with the counter vectorizer

In [13]:
qurantie_score_cv = data_process_svm_model(qurantie_data, counter_v, random_state=54)

No. of features in each class
   0    3914
 1      36
-1      24
Name: Sentiment, dtype: int64
No. of features in each class after SMOTE
   0    3914
 1    3914
-1    3914
Name: Sentiment, dtype: int64
model confusion matrix

[[  1   0   5]
 [ 46 270 994]
 [  2   2   5]] 

model classificaiton report

              precision    recall  f1-score   support

          -1       0.17      0.02      0.04        49
           0       0.21      0.99      0.34       272
           1       0.56      0.00      0.01      1004

    accuracy                           0.21      1325
   macro avg       0.31      0.34      0.13      1325
weighted avg       0.47      0.21      0.08      1325



## Qurantien data with the TFID vectorizer

In [14]:
qurantie_score_cv = data_process_svm_model(qurantie_data, counter_t, random_state=49)

No. of features in each class
   0    3913
 1      36
-1      25
Name: Sentiment, dtype: int64
No. of features in each class after SMOTE
   0    3913
-1    3913
 1    3913
Name: Sentiment, dtype: int64
model confusion matrix

[[   1    4    0]
 [   0 1311    0]
 [   0    9    0]] 

model classificaiton report

              precision    recall  f1-score   support

          -1       0.20      1.00      0.33         1
           0       1.00      0.99      1.00      1324
           1       0.00      0.00      0.00         0

    accuracy                           0.99      1325
   macro avg       0.40      0.66      0.44      1325
weighted avg       1.00      0.99      0.99      1325



/home/dp/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Social Distancing sentiment data analysis with the machine learning model

In [15]:
soc_data = pd.read_csv('soc_distance_sentiment_score.csv')
soc_data.head()

date  \
0  2020-10-30 22:06:12+00:00   
1  2020-10-30 21:09:12+00:00   
2  2020-10-30 19:36:57+00:00   
3  2020-10-30 11:51:33+00:00   
4  2020-10-30 11:04:50+00:00   

                                             content  \
0                               social distancing w/   
1  really impressed _nz strongly recommending mas...   
2  great work australia weve mildest flu season e...   
3  population especially urban metropolis, people...   
4  tapi ada sedikit kelakar social distancing nnt...   

                                          POS_tagged  \
0  [('social', 'a'), ('distancing', 'n'), ('w/', ...   
1  [('really', 'r'), ('impressed', 'a'), ('_nz', ...   
2  [('great', 'a'), ('work', 'n'), ('australia', ...   
3  [('population', 'n'), ('especially', 'r'), ('u...   
4  [('tapi', 'n'), ('ada', 'v'), ('sedikit', 'a')...   

                                               Lemma  Polarity  Sentiment  
0                                 socialdistancingw/       0.0          0  
1  reallyimpressed_nzstronglyrecommendmaskremindp...       0.0          0  
2  greatworkaustraliawevemildfluseasonever.highra...       0.0          0  
3  populationespeciallyurbanmetropolis,peoplepers...       0.0          0  
4  tapiadasedikitkelakarsocialdistancennti🤣🤣🤣tpmn...       0.0          0

## SOC data with the counter vectorizer

In [16]:
soc_score = data_process_svm_model(soc_data, counter_v, random_state=54)

No. of features in each class
   0    5001
 1      51
-1      33
Name: Sentiment, dtype: int64
No. of features in each class after SMOTE
   0    5001
-1    5001
 1    5001
Name: Sentiment, dtype: int64
model confusion matrix

[[   1    1    2]
 [  28  462 1185]
 [   0    2   14]] 

model classificaiton report

              precision    recall  f1-score   support

          -1       0.25      0.03      0.06        29
           0       0.28      0.99      0.43       465
           1       0.88      0.01      0.02      1201

    accuracy                           0.28      1695
   macro avg       0.47      0.35      0.17      1695
weighted avg       0.70      0.28      0.14      1695



## SOC data with the tfid vectorizer

In [17]:
soc_score = data_process_svm_model(soc_data, counter_v, random_state=54)

No. of features in each class
   0    5001
 1      51
-1      33
Name: Sentiment, dtype: int64
No. of features in each class after SMOTE
   0    5001
-1    5001
 1    5001
Name: Sentiment, dtype: int64
model confusion matrix

[[   1    1    2]
 [  28  462 1185]
 [   0    2   14]] 

model classificaiton report

              precision    recall  f1-score   support

          -1       0.25      0.03      0.06        29
           0       0.28      0.99      0.43       465
           1       0.88      0.01      0.02      1201

    accuracy                           0.28      1695
   macro avg       0.47      0.35      0.17      1695
weighted avg       0.70      0.28      0.14      1695



# Vaccine data sentiment analysis using machine learning model

In [18]:
vacc_data = pd.read_csv('vaccine_sentiment_score.csv')
vacc_data.head()

date  \
0  2020-10-30 21:43:08+00:00   
1  2020-10-30 15:43:24+00:00   
2  2020-10-30 14:00:59+00:00   
3  2020-10-30 09:37:53+00:00   
4  2020-10-30 06:36:20+00:00   

                                             content  \
0        _fletcher hope ➕decent president ➕vaccine ✅   
1  date someone who..? 1 - done 2 - lyfe 3 - dont...   
2         offer free covid vaccines apple fanboys 😉😉   
3              shaa allah ate. vaccine nalang kulang   
4  great modig pm modi says indians will coronavi...   

                                          POS_tagged  \
0  [('_fletcher', None), ('hope', 'n'), ('➕decent...   
1  [('date', 'n'), ('someone', 'n'), ('..', 'v'),...   
2  [('offer', 'n'), ('free', 'a'), ('covid', 'n')...   
3  [('shaa', 'n'), ('allah', 'n'), ('ate', 'n'), ...   
4  [('great', 'a'), ('modig', 'n'), ('pm', 'n'), ...   

                                               Lemma  Polarity  Sentiment  
0             _fletcherhope➕decentpresident➕vaccine✅       0.0          0  
1  datesomeone..?1-do2-lyfe3-dontthink?4-nahh..5-...       0.0          0  
2                offerfreecovidvaccineapplefanboys😉😉       0.0          0  
3                   shaaallahate.vaccinenalangkulang       0.0          0  
4  greatmodigpmmodisayindiancoronavirusvaccine,ex...       0.0          0

## Vaccine dataset analysis with the counter vectorizer

In [19]:
vacc_score = data_process_svm_model(vacc_data, counter_v, random_state=1)

No. of features in each class
   0    1505
 1      11
-1       6
Name: Sentiment, dtype: int64
No. of features in each class after SMOTE
   0    1505
 1    1505
-1    1505
Name: Sentiment, dtype: int64
model confusion matrix

[[  1   0   0]
 [337 136  28]
 [  5   1   0]] 

model classificaiton report

              precision    recall  f1-score   support

          -1       1.00      0.00      0.01       343
           0       0.27      0.99      0.43       137
           1       0.00      0.00      0.00        28

    accuracy                           0.27       508
   macro avg       0.42      0.33      0.14       508
weighted avg       0.75      0.27      0.12       508



## Vaccine dataset analysis with the tfid vectorizer

In [20]:
vacc_score_tfid = data_process_svm_model(vacc_data, counter_t, random_state=1)

No. of features in each class
   0    1505
 1      11
-1       6
Name: Sentiment, dtype: int64
No. of features in each class after SMOTE
   0    1505
 1    1505
-1    1505
Name: Sentiment, dtype: int64
model confusion matrix

[[  0   1   0]
 [  0 501   0]
 [  0   6   0]] 

model classificaiton report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       1.00      0.99      0.99       508
           1       0.00      0.00      0.00         0

    accuracy                           0.99       508
   macro avg       0.33      0.33      0.33       508
weighted avg       1.00      0.99      0.99       508



/home/dp/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dp/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
